--- 
before_install: 
  - "sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54"
  - "echo \"deb https://dist.crystal-lang.org/apt crystal main\" > /etc/apt/sources.list.d/crystal.list"
  - "sudo apt-get update"
before_script: 
  - "crystal deps --production"
install: 
  - "sudo apt-get install libbsd-dev libedit-dev libevent-core-2.0-5 libevent-dev libevent-extra-2.0-5 libevent-openssl-2.0-5 libevent-pthreads-2.0-5 libgmp-dev libgmpxx4ldbl libssl-dev libxml2-dev libyaml-dev libreadline-dev automake libtool git llvm libpcre3-dev build-essential crystal -y"
language: crystal
script: 
  - "crystal spec spec/*"
sudo: required