language: generic

os:
  - linux

before_install:
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
  - echo "deb http://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
  - sudo apt-get update
install:
  - sudo apt-get install crystal
before_script:
  - crystal deps --production
script:
  - crystal spec spec/*