sudo: required

services:
  - docker

before_install:
  - docker build -t crystal .
  - docker run -d -p 127.0.0.1:80:1337 --name crystal crystal"

before_script:
  - crystal deps --production

script:
  - docker ps | grep -q crystal
  - crystal spec spec/*

notifications:
  email: false